# Generated by Django 4.1.4 on 2023-01-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('jname', models.CharField(max_length=20)),
                ('jtype', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=20)),
                ('wtype', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=20)),
                ('exp', models.CharField(choices=[('0-1', '0-1'), ('2-5', '2-5'), ('6-10', '6-10')], max_length=20)),
            ],
        ),
    ]
