# Generated by Django 4.1.4 on 2023-01-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0002_pagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='cname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='exp',
            field=models.CharField(choices=[('0-1', '0-1'), ('2-5', '2-5'), ('6-10', '6-10')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='jname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='jtype',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='wtype',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=30),
        ),
    ]
