# Generated by Django 4.1.4 on 2023-01-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0003_alter_pagemodel_cname_alter_pagemodel_exp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='jobportalapp/static')),
                ('fname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='jobportalapp/static')),
                ('education', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
