# Generated by Django 4.1.4 on 2023-01-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0004_profilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='applymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='jobportalapp/static')),
                ('education', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
