# Generated by Django 4.1.4 on 2023-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0006_applymodel_company_applymodel_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('jname', models.CharField(max_length=30)),
                ('jtype', models.CharField(max_length=30)),
                ('wtype', models.CharField(max_length=30)),
                ('exp', models.CharField(max_length=30)),
            ],
        ),
    ]
